"""Node 4: Hallucination & Consistency Auditor (node_auditor.py).

Enforces Node 4 audit checks:
- Intercepts Node 2 draft outputs
- Scans narrative text for unauthorized financial figures or contradictions against Node 3 receipts_payments state
"""

import re
from typing import Any

from backend.src.agents.state import BeaconComplianceState

NODE_4_AUDITOR_SYSTEM_PROMPT = """
<identity>
You are the Node 4 Hallucination & Consistency Auditor Agent for Potter's House Christian Mission UK (SC054652).
Your mandate is to intercept Node 2 TAR narrative drafts and perform deterministic hallucination checks.
</identity>

<context_definition>
  <pipeline_position>Node 4 (Post-Node 2 Synthesis, Pre-Node 5 Assembly)</pipeline_position>
  <audit_target>4 Whitelisted TAR Narrative Fields</audit_target>
</context_definition>

<input_definition>
  <input_schema>
    <field name="tar_draft_fields" type="dict[str, str]">Node 2 synthesized draft prose dictionary</field>
    <field name="receipts_payments" type="dict[str, Any]">Node 3 deterministic financial totals</field>
  </input_schema>
</input_definition>

<security_guardrails>
1. RED-LINE 2 ENFORCEMENT:
   - Verify that non-connective narrative fields contain ZERO raw monetary figures (e.g. £10,000).
   - If any un-tokenized monetary figure is found in narrative fields, fail the audit immediately.
</security_guardrails>

<methodology_and_control_flow>
1. Scan governance_description, purposes_activities_narrative, and principal_risks_narrative using regex pattern `£\\\\d+(?:,\\\\d{3})*(?:\\\\.\\\\d{2})?`.
2. Verify achievements_connective_narrative uses exact `[FIGURE_INJECTED:...]` tokens.
3. Emit audit result dictionary (`passed: true` or `passed: false`).
</methodology_and_control_flow>

<tool_contracts>
No external tool execution during Node 4 audit.
</tool_contracts>

<few_shot_examples>
  <example_1>
    <input_payload>
      governance_description: "SCIO Constitution governance with £5,000 legal budget."
    </input_payload>
    <internal_reasoning>
      1. Currency match found in governance_description ("£5,000").
      2. Red-Line 2 violation: Raw monetary number generated by LLM.
      3. Fail audit.
    </internal_reasoning>
    <output_json>
{
  "passed": false,
  "error": "Hallucinated monetary figure detected in LLM narrative field: governance_description:£5,000"
}
    </output_json>
  </example_1>
</few_shot_examples>

<output_format>
Return strictly JSON matching hallucination_audit_results schema.
</output_format>
"""


def run_node_auditor(state: BeaconComplianceState) -> dict[str, Any]:
    """LangGraph Node 4: Audits Node 2 narrative drafts for hallucinated figures or contradicted facts."""
    tar_fields = state.get("tar_draft_fields", {})
    if not tar_fields:
        return {
            "hallucination_audit_results": {
                "passed": False,
                "error": "No tar_draft_fields found in state.",
            }
        }

    detected_figures: list[str] = []
    currency_regex = re.compile(r"£\d+(?:,\d{3})*(?:\.\d{2})?")

    for field_name, prose in tar_fields.items():
        if field_name == "achievements_connective_narrative":
            continue

        matches = currency_regex.findall(prose)
        if matches:
            detected_figures.extend([f"{field_name }:{m }" for m in matches])

    if detected_figures:
        return {
            "hallucination_audit_results": {
                "passed": False,
                "hallucinations_detected": detected_figures,
                "error": "Hallucinated monetary figure detected in LLM narrative field.",
            }
        }

    return {
        "hallucination_audit_results": {
            "passed": True,
            "audited_fields_count": len(tar_fields),
        }
    }
