name = "beacon-compliance-backend"
main = "backend/src/api/main.py"
compatibility_date = "2026-08-12"
compatibility_flags = ["python_workers"]

[vars]
APP_ENV = "production"
CHARITY_NUMBER = "SC054652"

[[d1_databases]]
binding = "DB"
database_name = "beacon-compliance-d1"
database_id = "ae9bc1a9-395d-468a-891e-172587c73189"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "R2_STORAGE"
bucket_name = "beacon-compliance-r2-prod"
